#!/bin/bash

tool=$1
target=$2

if [ -z "$tool" ] || [ -z "$target" ]; then
  echo "Usage: ./recon-tool <tool> <target>"
  echo "Example: ./recon-tool nmap 192.168.1.10"
  exit 1
fi

case $tool in
  nmap)
    nmap $target
    ;;
  nikto)
    nikto -h $target
    ;;
  whatweb)
    whatweb $target
    ;;
  netdiscover)
    netdiscover -r $target
    ;;
  arp-scan)
    arp-scan $target
    ;;
  ping)
    ping -c 4 $target
    ;;
  traceroute)
    traceroute $target
    ;;
  nslookup)
    nslookup $target
    ;;
  dig)
    dig $target
    ;;
  nbtscan)
    nbtscan $target
    ;;
  smb)
    smbclient -L //$target -N
    ;;
  *)
    echo "Tool not supported."
    echo "Supported tools:"
    echo "nmap nikto whatweb netdiscover arp-scan ping"
    echo "traceroute nslookup dig nbtscan smb"
    ;;
esac
